# Используем образ NGINX
FROM nginx:alpine

# Копируем файл page.html в стандартную директорию NGINX
COPY page.html /usr/share/nginx/html/page.html

# Указываем порт, который будет слушать сервер
EXPOSE 80
